/**
 * Tool-aware retention policy.
 *
 * CliffCompaction drops tool results over 500 characters on the grounds that
 * "the model can issue a new tool call from the preserved signature, so any
 * removed context remains recoverable". That premise holds for re-runnable
 * tools and fails for side-effecting ones: re-issuing `bash` may run `rm` or a
 * commit a second time, and re-issuing `edit` is not meaningful at all.
 *
 * Corpus measurement (64 real Pi sessions, 4720 tool results) is what makes the
 * split worth having: `read` is 29.7% of all context chars and 95% of its
 * results exceed 500 chars, while `bash` is 23.4% and only 54% do. So dropping
 * re-runnable output recovers the bulk of the win, and excerpting the rest
 * costs roughly 4 percentage points of total context.
 */

export type ToolClass = "drop" | "excerpt" | "keep";

/** Tools whose output can be regenerated by re-issuing the same call. */
export const DEFAULT_DROP_TOOLS: readonly string[] = ["read", "grep", "find", "ls"];

/** Tools whose output cannot be regenerated, or whose re-run has side effects. */
export const DEFAULT_EXCERPT_TOOLS: readonly string[] = [
	"bash",
	"powershell",
	"edit",
	"write",
];

export interface ToolPolicy {
	readonly dropTools: readonly string[];
	readonly excerptTools: readonly string[];
	/** Tools not named in either list. Excerpting is the safe default. */
	readonly unknown: ToolClass;
	/** Error results are never dropped — they are the highest-signal content. */
	readonly alwaysKeepErrors: boolean;
}

export const DEFAULT_TOOL_POLICY: ToolPolicy = {
	dropTools: DEFAULT_DROP_TOOLS,
	excerptTools: DEFAULT_EXCERPT_TOOLS,
	unknown: "excerpt",
	alwaysKeepErrors: true,
};

/**
 * What to do with a tool result longer than `resultMaxChars`.
 *
 * Order matters: an explicit list beats the unknown fallback, so a user can
 * move a tool between classes without touching the other list.
 */
export function classifyTool(toolName: string, policy: ToolPolicy): ToolClass {
	if (policy.dropTools.includes(toolName)) return "drop";
	if (policy.excerptTools.includes(toolName)) return "excerpt";
	return policy.unknown;
}
